import { chromium } from 'playwright-core';
const OUT = process.env.OUT;
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--use-angle=metal'] });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 720 } });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://localhost:5174/?room=OAK7&name=Eve&debug=1&tutorial=0');
await page.waitForFunction(() => window.__game);
const playerId = await page.evaluate(() => sessionStorage.getItem('mg-player'));
const post = (path, body) => page.evaluate(([p, b]) => fetch(p, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(b) }).then(r => r.json()), [path, body]);
const st = await page.evaluate(() => fetch('/api/state/OAK7').then(r => r.json()));
const bridge = st.world.trees.find(t => t.id === 'c2-bridge');
const walk = async (x, z) => { await page.evaluate(([a, b]) => window.__game.walkTo(a, b), [x, z]); await page.waitForFunction(() => window.__game.arrived(), null, { timeout: 30000 }); };
const click = async i => { const [x, y] = await page.evaluate(n => window.__game.pieceScreen(n), i); await page.mouse.click(x, y); await page.waitForTimeout(200); };
for (const [treeId, response] of [['t1', 0], ['c1-cake', 4], ['t3', 0], ['t2', 'no, it is the same amount because both are divided by 5']]) console.log(treeId, (await post('/api/answer', { worldId: 'OAK7', treeId, response, playerId, name: 'Eve' })).correct);
await page.waitForSelector('.modal.reflect', { timeout: 15000 });
await page.click('.ratings button:nth-child(3)'); await page.click('.modal.reflect button[type=submit]');
await page.waitForTimeout(3500);
await walk(0, bridge.pos[2] + 9); await walk(bridge.pos[0] * 0.5, bridge.pos[2] + 2.5);
await page.keyboard.press('KeyE');
await page.waitForFunction(() => window.__game.challengeOpen(), null, { timeout: 5000 });
await page.waitForTimeout(1200);
await page.screenshot({ path: `${OUT}/e1-bridge-open.png` });
for (const i of [0, 1, 2, 3, 4, 5]) await click(i);
console.log('count', await page.textContent('#challenge-n'));
await page.screenshot({ path: `${OUT}/e2-bridge-six.png` });
await page.click('#challenge-serve'); await page.waitForSelector('#fox:not([hidden])');
const r = page.waitForResponse(x => x.url().includes('/api/answer')); await page.keyboard.press('Digit3');
console.log('bridge correct', (await (await r).json()).correct);
await page.waitForTimeout(700); await page.screenshot({ path: `${OUT}/e3-bridge-done.png` });
console.log('errors:', errors);
await browser.close();
